### ISSUE TITLE
Support for alternative property names

### ISSUE THREAD

**Issue by stain** [openphacts/ops-search#1]
Some ontologies have non-obvious property names:

```
  ocrs:
    compound:
      graph: http://ops.rsc.org/
      properties:
        - cheminf:CHEMINF_000476
        - cheminf:CHEMINF_000465
        - cheminf:CHEMINF_000466
        - cheminf:CHEMINF_000490
```

Instead of indexing these as `CHEMINF_000476` a more user-friendly name like `title` should be specifiable in the configuration.

**Comment by stain** [comment]
Suggestion is something like:

``` yaml
        properties:
          - foaf:surname
          - dc:description
          - {
              sparql: "dbprop:shortDescription"
              variable: "shortDesc"
              jsonld: "dc:description"
            }
```

Here the keys `sparql` can support any SPARQL expression (including property paths #2 ), `variable` is what it is called in the query results, and `jsonld` what it is stored as in the indexed json-ld. If `variable` is not specified, it will fail.
